AWSTemplateFormatVersion: '2010-09-09'
Mapping:
  RegionMap:
    us-east-1:
      64:"ami-cb9ec1b1"
    ap-southeast-1:
      64:"ami-889cecf4"
Resources:
  myEC2Instence:
    Type: "AWS:EC2::Instance"
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", 'AMI']
      InstenceType: t2.micro      