---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create VPC'

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.20.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
        - Key: webvpc
          Value: production
  Subnnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AssignIpv6AddressOnCreation: false
      CidrBlock: 10.20.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: websubnet1
          Value: production
  Subnnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AssignIpv6AddressOnCreation: false
      CidrBlock: 10.20.2.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: websubnet2
          Value: production
   